import type { Floorplan, FurnitureItem, ThemePreset } from "./domain";

export const floorplans: Floorplan[] = [
  {
    id: "bh7-a6",
    name: "A6 圖面稽核房型",
    subtitle: "PDF 疊合稽核 Beta · p.2／3／7",
    area: "圖面寬 6.825 m",
    rooms: "主臥＋多功能室＋2 衛",
    accent: "#f4b86a",
    sourceStatus: "ready",
    shellVersion: "A6_SHELL_V3",
  },
  {
    id: "bh7-a11",
    name: "A11 圖面稽核房型",
    subtitle: "PDF 疊合稽核 Beta · p.13／14／18",
    area: "正面寬 8.65 m · 最大外框約 8.955 m",
    rooms: "主臥＋次臥＋多功能室＋2 衛",
    accent: "#87bba8",
    sourceStatus: "ready",
    shellVersion: "A11_SHELL_V1",
  },
  {
    id: "proposal-27",
    name: "27 坪提案型",
    subtitle: "待建商提供正式戶別圖面",
    area: "約 27 坪",
    rooms: "房數待正式圖面確認",
    accent: "#9ba8cf",
    sourceStatus: "awaiting_source",
  },
  {
    id: "proposal-39",
    name: "39 坪提案型",
    subtitle: "待建商提供正式戶別圖面",
    area: "約 39 坪",
    rooms: "房數待正式圖面確認",
    accent: "#d48a72",
    sourceStatus: "awaiting_source",
  },
];

export const themes: ThemePreset[] = [
  {
    id: "sunny",
    name: "日光慢生活",
    english: "Soft Japandi",
    description: "暖木、奶油色與留白，讓兩人日常慢下來。",
    palette: ["#f4d7aa", "#f7efe1", "#8ba58f"],
    emoji: "☀️",
  },
  {
    id: "urban",
    name: "都會品味宅",
    english: "Urban Modern",
    description: "深色輪廓、低飽和材質，簡潔但不單調。",
    palette: ["#27333c", "#d8c8ae", "#d97c5f"],
    emoji: "🌆",
  },
  {
    id: "family",
    name: "親子成長家",
    english: "Growing Family",
    description: "可變收納、圓角與活動區，陪家一起長大。",
    palette: ["#f3c76d", "#8bb8c4", "#ef8f78"],
    emoji: "🧸",
  },
  {
    id: "pet",
    name: "毛孩共居所",
    english: "Pet Friendly",
    description: "耐磨、易清潔與低矮安全，每個角落都是日常。",
    palette: ["#84a98c", "#e7d6b1", "#ca6f57"],
    emoji: "🐾",
  },
  {
    id: "empty",
    name: "空屋創作",
    english: "Blank Canvas",
    description: "從零開始，把每一件家具放在你想要的位置。",
    palette: ["#f2eee6", "#d8d4cc", "#b7b1a8"],
    emoji: "✨",
  },
];

export const catalog: FurnitureItem[] = [
  {
    id: "sofa-cloud",
    sku: "HP-A475-AR-MEL-SO-02-C1AA23",
    assetVersion: "p1-1.1.0",
    name: "雙人休閒沙發",
    category: "living",
    brand: "Play Ground Living",
    brandKind: "owned",
    price: 42800,
    color: "#e08a68",
    accent: "#efb091",
    shape: "sofa",
    assetPath: "/assets/hero-room/sofa-soft.glb",
    size: { width: 1.56, depth: 0.84, height: 0.72 },
    stock: "in_stock",
  },
  {
    id: "table-pebble",
    sku: "HP-A475-AR-PLA-TB-01-93B567",
    assetVersion: "p1-1.1.0",
    name: "圓形茶几",
    category: "living",
    brand: "Play Ground Living",
    brandKind: "owned",
    price: 12800,
    color: "#f2ebe1",
    accent: "#ebe3d6",
    shape: "table",
    assetPath: "/assets/hero-room/table-pebble.glb",
    size: { width: 0.7, depth: 0.7, height: 0.38 },
    stock: "in_stock",
  },
  {
    id: "chair-breeze",
    sku: "HP-A475-AR-DON-LO-01-04C7E8",
    assetVersion: "p1-1.1.0",
    name: "甜甜圈四星腳休閒椅",
    category: "living",
    brand: "Play Ground Living",
    brandKind: "owned",
    price: 16800,
    color: "#c4a06e",
    accent: "#d8bc93",
    shape: "chair",
    assetPath: "/assets/hero-room/chair-breeze.glb",
    size: { width: 0.77, depth: 0.67, height: 0.76 },
    stock: "low_stock",
  },
  {
    id: "rug-meadow",
    sku: "PG-RG-021",
    assetVersion: "1.2.0",
    name: "草原手織地毯",
    category: "decor",
    brand: "Play Ground Living",
    brandKind: "owned",
    price: 8900,
    color: "#d2a76f",
    accent: "#f2dfbd",
    shape: "rug",
    size: { width: 2.5, depth: 1.65, height: 0.04 },
    stock: "in_stock",
  },
  {
    id: "lamp-moon",
    sku: "LM-221",
    assetVersion: "1.1.0",
    name: "小月球立燈",
    category: "decor",
    brand: "Lumi Maison",
    brandKind: "affiliate",
    cashbackRate: 3,
    price: 7600,
    color: "#f1c96d",
    accent: "#4d5d53",
    shape: "lamp",
    size: { width: 0.45, depth: 0.45, height: 1.55 },
    stock: "in_stock",
  },
  {
    id: "plant-olive",
    sku: "GR-OL-09",
    assetVersion: "1.4.0",
    name: "橄欖樹植栽",
    category: "decor",
    brand: "Green Room",
    brandKind: "affiliate",
    cashbackRate: 5,
    price: 3200,
    color: "#6d8f65",
    accent: "#c7815d",
    shape: "plant",
    size: { width: 0.72, depth: 0.72, height: 1.65 },
    stock: "in_stock",
  },
  {
    id: "shelf-cabin",
    sku: "PG-ST-012",
    assetVersion: "1.1.0",
    name: "小屋模組收納櫃",
    category: "living",
    brand: "Play Ground Living",
    brandKind: "owned",
    price: 21800,
    color: "#bc8b5f",
    accent: "#f0d8b9",
    shape: "shelf",
    size: { width: 1.5, depth: 0.42, height: 1.65 },
    stock: "in_stock",
  },
  {
    id: "bed-soft",
    sku: "PG-BD-004",
    assetVersion: "1.5.0",
    name: "綿島雙人床",
    category: "bedroom",
    brand: "Play Ground Living",
    brandKind: "owned",
    price: 36800,
    color: "#a9b6ca",
    accent: "#e8dfcf",
    shape: "bed",
    size: { width: 1.82, depth: 2.08, height: 0.88 },
    stock: "in_stock",
  },
  {
    id: "ikea-saltsjobaden",
    sku: "IKEA-195.999.18",
    assetVersion: "ikea-demo-1.1.0",
    name: "SALTSJÖBADEN 雙人座沙發",
    category: "living",
    brand: "IKEA",
    brandKind: "affiliate",
    partnershipStatus: "demo",
    productUrl: "https://www.ikea.com.tw/zh/products/sofas/sofas/saltsjobaden-spr-19599918",
    sourceUpdatedAt: "2026-08-01",
    price: 13990,
    color: "#d8cec0",
    accent: "#a97950",
    shape: "sofa",
    assetPath: "/assets/hero-room/ikea-saltsjobaden.glb",
    size: { width: 1.64, depth: 0.88, height: 0.89 },
    stock: "in_stock",
  },
  {
    id: "ikea-borgeby",
    sku: "IKEA-704.494.02",
    assetVersion: "ikea-demo-1.1.0",
    name: "BORGEBY 圓形咖啡桌",
    category: "living",
    brand: "IKEA",
    brandKind: "affiliate",
    partnershipStatus: "demo",
    productUrl: "https://www.ikea.com.tw/zh/products/armchairs-footstool-and-sofa-tables/sofa-tables/borgeby-art-70449402",
    sourceUpdatedAt: "2026-08-01",
    price: 3499,
    color: "#c79d70",
    accent: "#ead4b5",
    shape: "table",
    assetPath: "/assets/hero-room/ikea-borgeby.glb",
    size: { width: 0.7, depth: 0.7, height: 0.42 },
    stock: "in_stock",
  },
  {
    id: "ikea-ekenaset",
    sku: "IKEA-705.334.91",
    assetVersion: "ikea-demo-1.1.0",
    name: "EKENÄSET 扶手椅",
    category: "living",
    brand: "IKEA",
    brandKind: "affiliate",
    partnershipStatus: "demo",
    productUrl: "https://www.ikea.com.tw/zh/products/armchairs-footstool-and-sofa-tables/armchairs/ekenaset-art-70533491",
    sourceUpdatedAt: "2026-08-01",
    price: 6299,
    color: "#e8dfcf",
    accent: "#6d4a36",
    shape: "chair",
    assetPath: "/assets/hero-room/ikea-ekenaset.glb",
    size: { width: 0.64, depth: 0.78, height: 0.76 },
    stock: "low_stock",
  },
  {
    id: "ikea-stoense",
    sku: "IKEA-206.076.82",
    assetVersion: "ikea-demo-1.1.0",
    name: "STOENSE 米色短毛地毯",
    category: "decor",
    brand: "IKEA",
    brandKind: "affiliate",
    partnershipStatus: "demo",
    productUrl: "https://www.ikea.com.tw/zh/products/home-furnishing-rugs/rugs/stoense-art-20607682",
    sourceUpdatedAt: "2026-08-01",
    price: 2499,
    color: "#d7c4a8",
    accent: "#f2e8d7",
    shape: "rug",
    assetPath: "/assets/hero-room/ikea-stoense.glb",
    size: { width: 1.33, depth: 1.95, height: 0.018 },
    stock: "in_stock",
  },
  {
    id: "ikea-lauters",
    sku: "IKEA-604.050.50",
    assetVersion: "ikea-demo-1.1.0",
    name: "LAUTERS 梣木落地燈",
    category: "decor",
    brand: "IKEA",
    brandKind: "affiliate",
    partnershipStatus: "demo",
    productUrl: "https://www.ikea.com.tw/zh/products/luminaires/floor-lamps/lauters-art-60405050",
    sourceUpdatedAt: "2026-08-01",
    price: 2299,
    color: "#b98e61",
    accent: "#f3eadb",
    shape: "lamp",
    assetPath: "/assets/hero-room/ikea-lauters.glb",
    size: { width: 0.62, depth: 0.62, height: 1.51 },
    stock: "in_stock",
  },
  {
    id: "ikea-fejka-fig",
    sku: "IKEA-106.152.77",
    assetVersion: "ikea-demo-1.1.0",
    name: "FEJKA 垂葉榕人造盆栽",
    category: "decor",
    brand: "IKEA",
    brandKind: "affiliate",
    partnershipStatus: "demo",
    productUrl: "https://www.ikea.com.tw/zh/products/green-decoration/artificial-plants/fejka-art-10615277",
    sourceUpdatedAt: "2026-08-01",
    price: 1999,
    color: "#78936b",
    accent: "#b87854",
    shape: "plant",
    assetPath: "/assets/hero-room/ikea-fejka-fig.glb",
    size: { width: 0.72, depth: 0.72, height: 1.7 },
    stock: "out_of_stock",
  },
  {
    id: "ikea-kallax",
    sku: "IKEA-006.289.30",
    assetVersion: "ikea-demo-1.1.0",
    name: "KALLAX 2×3 層架組",
    category: "living",
    brand: "IKEA",
    brandKind: "affiliate",
    partnershipStatus: "demo",
    productUrl: "https://www.ikea.com.tw/zh/products/sideboard-cabinets/open-storage/kallax-art-00628930",
    sourceUpdatedAt: "2026-08-01",
    price: 2299,
    color: "#f0eee8",
    accent: "#c8a87a",
    shape: "shelf",
    assetPath: "/assets/hero-room/ikea-kallax.glb",
    size: { width: 0.765, depth: 0.39, height: 1.115 },
    stock: "in_stock",
  },
  {
    id: "table-pla-tb-02",
    sku: "HP-A475-AR-PLA-TB-02-9D2ADC",
    assetVersion: "p1-1.1.0",
    name: "圓形茶几",
    category: "living",
    brand: "Play Ground Living",
    brandKind: "owned",
    price: 1500,
    color: "#7ea8aa",
    accent: "#6f9a9c",
    shape: "table",
    assetPath: "/assets/hero-room/hp-a475-ar-pla-tb-02.glb",
    size: { width: 0.38, depth: 0.38, height: 0.46 },
    stock: "in_stock",
  },
  {
    id: "table-dme52-1000",
    sku: "HP-A213-DME52-B00DDF",
    assetVersion: "p1-1.1.0",
    name: "洽談桌",
    category: "dining",
    brand: "Play Ground Living",
    brandKind: "owned",
    price: 3400,
    color: "#c4a07a",
    accent: "#cfcbc4",
    shape: "table",
    assetPath: "/assets/hero-room/hp-a213-dme52-b00ddf.glb",
    size: { width: 1.0, depth: 1.0, height: 0.75 },
    stock: "in_stock",
  },
  {
    id: "table-dme52-800",
    sku: "HP-A213-DME52-0D4DB8",
    assetVersion: "p1-1.1.0",
    name: "洽談桌",
    category: "dining",
    brand: "Play Ground Living",
    brandKind: "owned",
    price: 3400,
    color: "#c4a07a",
    accent: "#cfcbc4",
    shape: "table",
    assetPath: "/assets/hero-room/hp-a213-dme52-0d4db8.glb",
    size: { width: 0.8, depth: 0.8, height: 0.75 },
    stock: "in_stock",
  },
];

export const ownedInitialFurnitureIds = [
  "rug-meadow",
  "sofa-cloud",
  "table-pebble",
  "table-pla-tb-02",
  "chair-breeze",
  "lamp-moon",
  "plant-olive",
  "table-dme52-1000",
  "bed-soft",
];

// Kept as the canonical launch preset for runtime validation and older adapters.
export const initialFurnitureIds = ownedInitialFurnitureIds;

export const ikeaDemoFurnitureIds = [
  "ikea-stoense",
  "ikea-saltsjobaden",
  "ikea-borgeby",
  "ikea-ekenaset",
  "ikea-lauters",
  "ikea-fejka-fig",
  "ikea-kallax",
];

// 初始配置中側向（-90°）擺放的家具：計算佔地時寬深互換
export const sideFacingFurnitureIds = ["sofa-cloud", "ikea-saltsjobaden", "shelf-cabin", "ikea-kallax"] as const;

// 日光慢生活加碼配置：讓首屏就是佈置完成的家（聯盟商品置於餐廳與多功能室）
export const sunnyBonusFurnitureIds = [
  "ikea-fejka-fig",
  "ikea-borgeby",
  "ikea-kallax",
  "ikea-lauters",
] as const;

export const themeFurnitureIds: Record<Exclude<ThemePreset["id"], "empty">, readonly string[]> = {
  sunny: [...ownedInitialFurnitureIds, ...sunnyBonusFurnitureIds],
  urban: ["rug-meadow", "sofa-cloud", "table-pebble", "table-pla-tb-02", "chair-breeze", "lamp-moon", "table-dme52-1000", "bed-soft"],
  family: ["rug-meadow", "sofa-cloud", "table-pebble", "table-pla-tb-02", "chair-breeze", "plant-olive", "table-dme52-1000", "bed-soft"],
  pet: ["rug-meadow", "sofa-cloud", "table-pebble", "table-pla-tb-02", "chair-breeze", "plant-olive", "table-dme52-1000", "bed-soft"],
};
