import type { Floorplan, FurnitureItem, ThemePreset } from "./domain";

export const floorplans: Floorplan[] = [
  {
    id: "a2",
    name: "A2 日光兩房",
    subtitle: "雙面採光·開放客餐廳",
    area: "26.8 坪",
    rooms: "2 房 2 廳 1 衛",
    accent: "#f4b86a",
  },
  {
    id: "b1",
    name: "B1 輕盈三房",
    subtitle: "回字動線·彈性多功能房",
    area: "34.5 坪",
    rooms: "3 房 2 廳 2 衛",
    accent: "#87bba8",
  },
  {
    id: "c3",
    name: "C3 景觀三房",
    subtitle: "大面窗景·獨立家事區",
    area: "42.2 坪",
    rooms: "3 房 2 廳 2 衛",
    accent: "#9ba8cf",
  },
];

export const themes: ThemePreset[] = [
  {
    id: "sunny",
    name: "日光慢生活",
    english: "Soft Japandi",
    description: "暖木、奶油色與留白，讓兩人日常慢下來。",
    palette: ["#f4d7aa", "#f7efe1", "#8ba58f"],
    emoji: "☀️",
  },
  {
    id: "urban",
    name: "都會品味宅",
    english: "Urban Modern",
    description: "深色輪廓、低飽和材質，簡潔但不單調。",
    palette: ["#27333c", "#d8c8ae", "#d97c5f"],
    emoji: "🌆",
  },
  {
    id: "family",
    name: "親子成長家",
    english: "Growing Family",
    description: "可變收納、圓角與活動區，陪家一起長大。",
    palette: ["#f3c76d", "#8bb8c4", "#ef8f78"],
    emoji: "🧸",
  },
  {
    id: "pet",
    name: "毛孩共居所",
    english: "Pet Friendly",
    description: "耐磨、易清潔與低矮安全，每個角落都是日常。",
    palette: ["#84a98c", "#e7d6b1", "#ca6f57"],
    emoji: "🐾",
  },
  {
    id: "empty",
    name: "空屋創作",
    english: "Blank Canvas",
    description: "從零開始，把每一件家具放在你想要的位置。",
    palette: ["#f2eee6", "#d8d4cc", "#b7b1a8"],
    emoji: "✨",
  },
];

export const catalog: FurnitureItem[] = [
  {
    id: "sofa-cloud",
    sku: "PG-SF-001",
    assetVersion: "1.2.0",
    name: "雲朵雙人沙發",
    category: "living",
    brand: "Play Ground Living",
    brandKind: "owned",
    price: 42800,
    color: "#df9d75",
    accent: "#f5d4bb",
    shape: "sofa",
    size: { width: 2.15, depth: 0.92, height: 0.82 },
    stock: "in_stock",
  },
  {
    id: "table-pebble",
    sku: "PG-TB-014",
    assetVersion: "1.0.3",
    name: "小石橢圓桌",
    category: "living",
    brand: "Play Ground Living",
    brandKind: "owned",
    price: 12800,
    color: "#b9845a",
    accent: "#e6c89f",
    shape: "table",
    size: { width: 1.1, depth: 0.72, height: 0.38 },
    stock: "in_stock",
  },
  {
    id: "chair-breeze",
    sku: "PG-CH-008",
    assetVersion: "2.0.1",
    name: "微風扶手椅",
    category: "living",
    brand: "Play Ground Living",
    brandKind: "owned",
    price: 16800,
    color: "#7ca79a",
    accent: "#d9c7a1",
    shape: "chair",
    size: { width: 0.78, depth: 0.78, height: 0.78 },
    stock: "low_stock",
  },
  {
    id: "rug-meadow",
    sku: "PG-RG-021",
    assetVersion: "1.1.0",
    name: "草原手織地毯",
    category: "decor",
    brand: "Play Ground Living",
    brandKind: "owned",
    price: 8900,
    color: "#d2a76f",
    accent: "#f2dfbd",
    shape: "rug",
    size: { width: 2.5, depth: 1.65, height: 0.04 },
    stock: "in_stock",
  },
  {
    id: "lamp-moon",
    sku: "LM-221",
    assetVersion: "1.0.0",
    name: "小月球立燈",
    category: "decor",
    brand: "Lumi Maison",
    brandKind: "affiliate",
    cashbackRate: 3,
    price: 7600,
    color: "#f1c96d",
    accent: "#4d5d53",
    shape: "lamp",
    size: { width: 0.45, depth: 0.45, height: 1.55 },
    stock: "in_stock",
  },
  {
    id: "plant-olive",
    sku: "GR-OL-09",
    assetVersion: "1.3.2",
    name: "橄欖樹植栽",
    category: "decor",
    brand: "Green Room",
    brandKind: "affiliate",
    cashbackRate: 5,
    price: 3200,
    color: "#6d8f65",
    accent: "#c7815d",
    shape: "plant",
    size: { width: 0.72, depth: 0.72, height: 1.65 },
    stock: "in_stock",
  },
  {
    id: "shelf-cabin",
    sku: "PG-ST-012",
    assetVersion: "1.0.5",
    name: "小屋模組收納櫃",
    category: "living",
    brand: "Play Ground Living",
    brandKind: "owned",
    price: 21800,
    color: "#bc8b5f",
    accent: "#f0d8b9",
    shape: "shelf",
    size: { width: 1.5, depth: 0.42, height: 1.65 },
    stock: "in_stock",
  },
  {
    id: "bed-soft",
    sku: "PG-BD-004",
    assetVersion: "1.4.0",
    name: "綿島雙人床",
    category: "bedroom",
    brand: "Play Ground Living",
    brandKind: "owned",
    price: 36800,
    color: "#a9b6ca",
    accent: "#e8dfcf",
    shape: "bed",
    size: { width: 1.82, depth: 2.08, height: 0.88 },
    stock: "in_stock",
  },
];

export const initialFurnitureIds = [
  "rug-meadow",
  "sofa-cloud",
  "table-pebble",
  "chair-breeze",
  "lamp-moon",
  "plant-olive",
  "shelf-cabin",
];
